language: ruby
cache: bundler
os:
- linux
rvm:
- jruby
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.0
- 2.1.5
jobs:
  include:
  - os: osx
    osx_image: xcode7.3
    rvm: 1.9.3
  - os: osx
    rvm: 2.0.0
  - os: osx
    rvm: 2.1.0
  - os: osx
    rvm: 2.1.5
  - stage: deploy
    if: branch = master
    os: linux
    rvm: 2.0.0
    deploy:
      provider: rubygems
      api_key:
        secure: KcBpkFaes74KGMm8X/rRA8e13+t3PmkefsAvOAR+iF4g1GyuLSPkP92Fb9vFfsXBph+qmFh5rNa2lIRf/3RXW6COxY7CMMaARxUfJOKE0rmIwF0qfKI+RZDh6abg92iYngunMZVN8WVft6Lv9ZTOYCWxr1Zs1Ll/Rl4PfvHNd1g=
      gem: travis
      on:
        repo: travis-ci/travis.rb
        ruby: 2.0.0
notifications:
  slack:
    secure: KXEq4uAoVJTXz7syUH9ua4sQDlT9Qwp50x2jrz6hLw1bL5o/REGHn/O+xCbSl7aGrthVfvs7ZcXRFiAPAwaQa3ZOG8rd/PO+UmwUiABTdxztJfClmEnU2nuqV8SnZ0xze03HId9Cn9LGNGtR4lLYNfVDmlP0r514GN6FqmZF0QwPX2fo6FX0ZdRah8mwPOSfaFXysL8r+XDhvCqz1mjhbVKI8jbsnATlpQBAgb/9AAsmNVw52qv5qdHiufwecIJRxSGD+LPq/k19A4gNf60LUJZRZZpsJlrnSwQcnxMnsCxowjBwu5g2lxrwu/zFhlYo76659ZjFil/b6Ui+/4EQhxR1CeG4RyEtOwt+XwtRHdT/ieL2DEYv+7m/XYjf7RPISlsZ1yS1FKnK92COtUdMP22peQKEa+PMGqfKwufhzmvzLhiJ/Moln1cB7rBTeK+fnjHRz/Mo/mwZ0SqAcFLAwN817iFRvqsVKqniTuDIh1EM/wjQbgkyR95h6GMmjiWrD7i4uQRJ6KGclyBYfWdU7jVnYvaMYmOQ3HGpOXolm9OQsqwz5SdHmmpEWk520tOEpfHHjaErpKDKqT4llRp1t1yWJ9zGAOkOBy6/ptwYl0VtnJoscdiJfD6wXgWUJNGVhrileKPCEY1JGtJQ2hmbThiy81NABwvECuN+4Vo6pmw=
